#!/bin/bash

title logwatch

LOGWATCH_TS="$AA_CONFIGDIR/logwatch_ts"
touch "$LOGWATCH_TS"

du -sh /var/log

if chk_int "$LOGWATCH_TS" "60*60*24" || chk_all; then
	pass
else
	echo "Skipping..."
	exit 0
fi


sudo /usr/sbin/logwatch --range "since 24 hours ago for those hours"
