#!/bin/bash
title mtail

MTAIL_TS="$AA_CONFIGDIR/mtail_ts"
touch "$MTAIL_TS"

command -v mtail &> /dev/null || { echo "mtail is a required dependency for ${0}"; exit; }

if chk_int "$MTAIL_TS" "60*60*06" || chk_all; then
	pass
else
	echo "Skipping..."
	exit 0
fi

sudo $SUDOFLAG mtail --one_shot --logs /var/log/auth.log --progs ${SCRIPTBIN}/mtail_progs/
