#!/bin/bash

title "Examine SSL and Domains"

SSL_TS="$AA_CONFIGDIR/SSL_ts"
touch "$SSL_TS"

if chk_int "$SSL_TS" "60*60*24" || chk_all; then
	pass
else
	echo "Skipping..."
	exit 0
fi

command -v domanager &> /dev/null || { echo "Git is a required dependency for ${0}"; exit; }

( cd $AA_CONFIGDIR && domanager )
echo '
`certbot -d ajpikul.com,*.ajpikul.com --manual --preferred-challenges certonly`
`certbot renew` might work? certs must be readable'

exit0
