#!/bin/bash
title system_status

OUTPUT=$(systemctl list-units --state=failed --all 2>&1)
if ! echo -e "$OUTPUT" | grep -qe "0 loaded units listed"; then
	echo "${BOLD}Failed services:${NORM}"
	echo -e "$OUTPUT"
fi
