#!/bin/bash
title system_status

OUTPUT=$(systemctl list-units --state=failed --all &> 1)
if [ -n "$OUTPUT" ]; then
	echo "${BOLD}Failed services:${NORM}"
	echo -e "$OUTPUT"
fi

OUTPUT=$(journalctl -p 3 -xb)
if ! echo "$OUTPUT" | tail -n 1 | grep -qe "-- No entries --"; then
	echo "${BOLD}Issues in the log:${NORM}"
	echo "$OUTPUT"
fi
